import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import '@radix-ui/themes/styles.css'

import { Providers } from '@/lib/components/providers'

import { Theme } from '@radix-ui/themes'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const views = [
	{
		href: '/',
		label: 'Fonts',
	},
	{
		href: '/favorites',
		label: 'Favorites',
	},
]

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<Theme accentColor="cyan" grayColor="sage" radius="large">
					<Providers>
						{/*<nav className="container mx-auto grid place-items-center place-content-center py-8 px-8">
							<ul className="grid grid-flow-col gap-3">
								{views.map(view => (
									<li key={view.href}>
										<a
											href={view.href}
											className="px-4 py-1.5 font-medium bg-neutral-100 hover:bg-neutral-200 transition ease-out duration-300 rounded-full"
										>
											{view.label}
										</a>
									</li>
								))}
							</ul>
						</nav>*/}

						<main>{children}</main>
					</Providers>
				</Theme>
			</body>
		</html>
	)
}
