import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import '@radix-ui/themes/styles.css'

import { Providers } from '@/lib/components/providers'

import { Theme } from '@radix-ui/themes'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const views = [
	{
		href: '/',
		label: 'Fonts',
	},
	{
		href: '/favorites',
		label: 'Favorites',
	},
]

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<Theme accentColor="cyan" grayColor="gray" radius="large">
					<Providers>
						<main>{children}</main>
					</Providers>
				</Theme>
			</body>
		</html>
	)
}
